import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialSetup1772637853189 implements MigrationInterface {
    name = 'InitialSetup1772637853189'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "App_Subscriptions" DROP CONSTRAINT "FK_f6a5238b4fd16e1d6bf898b6a7e"`);
        await queryRunner.query(`ALTER TABLE "App_Orders" DROP CONSTRAINT "FK_5627a665b2dbd39f68666da05b8"`);
        await queryRunner.query(`DROP INDEX "public"."idx_test_options_is_active"`);
        await queryRunner.query(`DROP INDEX "public"."idx_app_user_profiles_is_active"`);
        await queryRunner.query(`DROP INDEX "public"."idx_app_user_profiles_name"`);
        await queryRunner.query(`DROP INDEX "public"."idx_tests_is_active"`);
        await queryRunner.query(`DROP INDEX "public"."idx_tests_title"`);
        await queryRunner.query(`DROP INDEX "public"."idx_test_questions_is_active"`);
        await queryRunner.query(`DROP INDEX "public"."idx_test_results_is_active"`);
        await queryRunner.query(`DROP INDEX "public"."idx_test_attempts_is_active"`);
        await queryRunner.query(`DROP INDEX "public"."idx_test_attempts_user_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_test_attempts_test_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_app_payment_sessions_is_active"`);
        await queryRunner.query(`DROP INDEX "public"."idx_app_payments_is_active"`);
        await queryRunner.query(`DROP INDEX "public"."idx_app_subscriptions_is_active"`);
        await queryRunner.query(`DROP INDEX "public"."idx_app_order_amounts_is_active"`);
        await queryRunner.query(`DROP INDEX "public"."idx_app_orders_is_active"`);
        await queryRunner.query(`DROP INDEX "public"."idx_log_device_is_active"`);
        await queryRunner.query(`DROP INDEX "public"."idx_log_device_ip"`);
        await queryRunner.query(`DROP INDEX "public"."idx_log_error_is_active"`);
        await queryRunner.query(`DROP INDEX "public"."idx_log_error_status"`);
        await queryRunner.query(`DROP INDEX "public"."idx_log_response_is_active"`);
        await queryRunner.query(`DROP INDEX "public"."idx_log_response_request_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_log_response_status"`);
        await queryRunner.query(`DROP INDEX "public"."idx_log_request_is_active"`);
        await queryRunner.query(`DROP INDEX "public"."idx_log_request_user_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_log_request_device_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_log_request_action"`);
        await queryRunner.query(`DROP INDEX "public"."idx_auth_otps_is_active"`);
        await queryRunner.query(`DROP INDEX "public"."idx_auth_otps_user_id_channel_type_expires_at"`);
        await queryRunner.query(`DROP INDEX "public"."idx_auth_otps_user_id_channel_type_created_at"`);
        await queryRunner.query(`DROP INDEX "public"."idx_auth_provider_is_active"`);
        await queryRunner.query(`DROP INDEX "public"."idx_auth_provider_provider_provider_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_auth_sessions_is_active"`);
        await queryRunner.query(`DROP INDEX "public"."idx_auth_tokens_is_active"`);
        await queryRunner.query(`DROP INDEX "public"."idx_auth_tokens_user_id_type_expires_at"`);
        await queryRunner.query(`DROP INDEX "public"."idx_auth_tokens_expires_at"`);
        await queryRunner.query(`DROP INDEX "public"."idx_auth_tokens_user_id_type_is_revoked"`);
        await queryRunner.query(`DROP INDEX "public"."idx_auth_tokens_type_token"`);
        await queryRunner.query(`DROP INDEX "public"."idx_auth_tokens_token"`);
        await queryRunner.query(`DROP INDEX "public"."idx_app_users_is_active"`);
        await queryRunner.query(`DROP INDEX "public"."idx_app_users_email"`);
        await queryRunner.query(`DROP INDEX "public"."idx_app_users_phone"`);
        await queryRunner.query(`DROP INDEX "public"."idx_app_users_phone_is_active"`);
        await queryRunner.query(`DROP INDEX "public"."idx_app_users_email_is_active"`);
        await queryRunner.query(`DROP INDEX "public"."idx_app_clients_is_active"`);
        await queryRunner.query(`DROP INDEX "public"."idx_app_clients_name"`);
        await queryRunner.query(`DROP INDEX "public"."idx_meta_global_orgs_is_active"`);
        await queryRunner.query(`DROP INDEX "public"."idx_meta_geo_water_bodies_is_active"`);
        await queryRunner.query(`DROP INDEX "public"."idx_meta_geo_water_bodies_name"`);
        await queryRunner.query(`DROP INDEX "public"."idx_meta_geo_rivers_is_active"`);
        await queryRunner.query(`DROP INDEX "public"."idx_meta_geo_rivers_name"`);
        await queryRunner.query(`DROP INDEX "public"."idx_meta_geo_deserts_is_active"`);
        await queryRunner.query(`DROP INDEX "public"."idx_meta_geo_countries_is_active"`);
        await queryRunner.query(`DROP INDEX "public"."idx_meta_geo_countries_dial_code"`);
        await queryRunner.query(`DROP INDEX "public"."idx_meta_geo_countries_code_a3"`);
        await queryRunner.query(`DROP INDEX "public"."idx_meta_geo_countries_code_a2"`);
        await queryRunner.query(`DROP INDEX "public"."idx_meta_geo_continents_is_active"`);
        await queryRunner.query(`DROP INDEX "public"."idx_meta_geo_continents_name"`);
        await queryRunner.query(`DROP INDEX "public"."idx_meta_geo_continents_code"`);
        await queryRunner.query(`DROP INDEX "public"."idx_acd_comparison_items_is_active"`);
        await queryRunner.query(`DROP INDEX "public"."idx_acd_comparisons_is_active"`);
        await queryRunner.query(`DROP INDEX "public"."idx_acd_content_comparisons_is_active"`);
        await queryRunner.query(`DROP INDEX "public"."idx_acd_diagrams_is_active"`);
        await queryRunner.query(`DROP INDEX "public"."idx_acd_content_diagrams_is_active"`);
        await queryRunner.query(`DROP INDEX "public"."idx_acd_content_is_active"`);
        await queryRunner.query(`DROP INDEX "public"."idx_acd_syllabus_is_active"`);
        await queryRunner.query(`CREATE TABLE "App_Nodes" ("id" SERIAL NOT NULL, "uid" character varying(12) NOT NULL, "is_active" boolean NOT NULL DEFAULT true, "created_by" integer NOT NULL DEFAULT '0', "created_at" TIMESTAMP WITH TIME ZONE NOT NULL, "master" character(1) NOT NULL, "order" smallint NOT NULL DEFAULT '0', "label" character varying(50) NOT NULL, "avatar" character varying(50), "description" character varying(255), "description_long" character varying(511), "protected" boolean NOT NULL DEFAULT false, "meta" text array, CONSTRAINT "UQ_bd77c4905baae2a5e6eecde9c6b" UNIQUE ("uid"), CONSTRAINT "PK_62328f7ef09c4e0160a48b06006" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_a996499aa7897bb9715b7022f4" ON "App_Nodes" ("is_active") `);
        await queryRunner.query(`CREATE TABLE "App_Plans" ("id" SERIAL NOT NULL, "uid" character varying(12) NOT NULL, "is_active" boolean NOT NULL DEFAULT true, "created_by" integer NOT NULL DEFAULT '0', "created_at" TIMESTAMP WITH TIME ZONE NOT NULL, "type" character(1) NOT NULL, "bill_mode" character(1) NOT NULL, "currency" character(3) NOT NULL DEFAULT 'INR', "actual_price" numeric(8,2), "discount_price" numeric(8,2), "discount_rate" numeric(5,2), "node_id" integer NOT NULL, CONSTRAINT "UQ_a6427ba5df63f9cf3c6b4beee45" UNIQUE ("uid"), CONSTRAINT "PK_a22ec10022cb17bdd44e42c2efa" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_4c065ef3cc4a44f4327f3d043f" ON "App_Plans" ("is_active") `);
        await queryRunner.query(`ALTER TABLE "Meta_Global_Orgs" ALTER COLUMN "primary_function" DROP NOT NULL`);
        await queryRunner.query(`CREATE INDEX "IDX_b3463f4f4fc498924213c0fc1d" ON "Test_Options" ("is_active") `);
        await queryRunner.query(`CREATE INDEX "IDX_2b52ef874ff0a6b8698a409035" ON "App_User_Profiles" ("is_active") `);
        await queryRunner.query(`CREATE INDEX "IDX_946e625be5e5b268ad2675ec09" ON "App_User_Profiles" ("name") `);
        await queryRunner.query(`CREATE INDEX "IDX_9bb6c33098886ef04153a3f615" ON "Tests" ("is_active") `);
        await queryRunner.query(`CREATE INDEX "IDX_64534a51882e89c399fb7f17a9" ON "Tests" ("title") `);
        await queryRunner.query(`CREATE INDEX "IDX_a61ea4effa78ec28c32898ecf8" ON "Test_Questions" ("is_active") `);
        await queryRunner.query(`CREATE INDEX "IDX_985af56efa4dc0a270541c789c" ON "Test_Results" ("is_active") `);
        await queryRunner.query(`CREATE INDEX "IDX_66f0b945db916893c35c8002a8" ON "Test_Attempts" ("is_active") `);
        await queryRunner.query(`CREATE INDEX "IDX_1f45e771a78e8e360c34d02a33" ON "Test_Attempts" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_da2edacb664d1c9165ab9ecab4" ON "Test_Attempts" ("test_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_f4a1fe1deebded3e06e3849c7d" ON "App_Payment_Sessions" ("is_active") `);
        await queryRunner.query(`CREATE INDEX "IDX_17af54eb164f22204f7b6446a3" ON "App_Payments" ("is_active") `);
        await queryRunner.query(`CREATE INDEX "IDX_0d77c4c930691c477603bb006e" ON "App_Subscriptions" ("is_active") `);
        await queryRunner.query(`CREATE INDEX "IDX_3656c9c243379c7573c4000404" ON "App_Order_Amounts" ("is_active") `);
        await queryRunner.query(`CREATE INDEX "IDX_0cea8e3843fe84e3ca2d387dc0" ON "App_Orders" ("is_active") `);
        await queryRunner.query(`CREATE INDEX "IDX_f270a3832892a35339040fef36" ON "Log_Device" ("is_active") `);
        await queryRunner.query(`CREATE INDEX "IDX_f4ba3cd398bf8188701139816a" ON "Log_Device" ("ip") `);
        await queryRunner.query(`CREATE INDEX "IDX_17f330d29e4f9285a797f0fce8" ON "Log_Error" ("is_active") `);
        await queryRunner.query(`CREATE INDEX "IDX_6278117936c7c8d2ed850a5394" ON "Log_Error" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_b237ff6093ab521eaf9ad50dac" ON "Log_Response" ("is_active") `);
        await queryRunner.query(`CREATE INDEX "IDX_555b924db8997f03ec49e416e4" ON "Log_Response" ("request_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_ccc883b42da57062abb6520f5b" ON "Log_Response" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_c3808f42fcaf7082d2ea37fda9" ON "Log_Request" ("is_active") `);
        await queryRunner.query(`CREATE INDEX "IDX_924b42905e2cd10ed5fa820042" ON "Log_Request" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_220f6ad9ab1e0e47f88b8d16f4" ON "Log_Request" ("device_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_f5aff5920114252b7d12c0549e" ON "Log_Request" ("action") `);
        await queryRunner.query(`CREATE INDEX "IDX_418897925b209bfd2b5807b29f" ON "Auth_Otps" ("is_active") `);
        await queryRunner.query(`CREATE INDEX "IDX_ff6502b8ebdc94a9a7a73e197b" ON "Auth_Otps" ("user_id", "channel", "type", "expires_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_149d33f5b681601f1226a9cc29" ON "Auth_Otps" ("user_id", "channel", "type", "created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_feab35e90893152d0f6b3f0fbc" ON "Auth_Provider" ("is_active") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_cefcb8861290ef1baaf964c409" ON "Auth_Provider" ("provider", "provider_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_ed2a5de64bf5f1719e13506b8e" ON "Auth_Sessions" ("is_active") `);
        await queryRunner.query(`CREATE INDEX "IDX_ea60f81fb3a3df93407a9dbe99" ON "Auth_Tokens" ("is_active") `);
        await queryRunner.query(`CREATE INDEX "IDX_35d298e0b7d4f5204017045752" ON "Auth_Tokens" ("user_id", "type", "expires_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_ad32f77582c45444d25ecaa683" ON "Auth_Tokens" ("expires_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_73f288724f093c6cbe774fe5e9" ON "Auth_Tokens" ("user_id", "type", "is_revoked") `);
        await queryRunner.query(`CREATE INDEX "IDX_27d3dfde29b373d2969098de75" ON "Auth_Tokens" ("type", "token") `);
        await queryRunner.query(`CREATE INDEX "IDX_80f1763d5cfafc4a5193d89b1e" ON "Auth_Tokens" ("token") `);
        await queryRunner.query(`CREATE INDEX "IDX_156a9fed402cb96e877f4ca8e9" ON "App_Users" ("is_active") `);
        await queryRunner.query(`CREATE INDEX "IDX_1dd1db41c4a33bc92121e05fb7" ON "App_Users" ("email") `);
        await queryRunner.query(`CREATE INDEX "IDX_d31d7ce68d9bf75a11d957f81a" ON "App_Users" ("phone") `);
        await queryRunner.query(`CREATE INDEX "IDX_df1ac31e41efe8e985fdae0dbb" ON "App_Users" ("phone", "is_active") `);
        await queryRunner.query(`CREATE INDEX "IDX_ea7d09e61982b98a9920bdbc5e" ON "App_Users" ("email", "is_active") `);
        await queryRunner.query(`CREATE INDEX "IDX_2498407c7c048a8143d41bc52f" ON "App_Clients" ("is_active") `);
        await queryRunner.query(`CREATE INDEX "IDX_3dafe8e504d69068a2e4028a57" ON "App_Clients" ("name") `);
        await queryRunner.query(`CREATE INDEX "IDX_752fbf19f9ef9241b729d51865" ON "Meta_Global_Orgs" ("is_active") `);
        await queryRunner.query(`CREATE INDEX "IDX_c5353e390a3d545087d02c929b" ON "Meta_Geo_Water_Bodies" ("is_active") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_b075f4336109e9bab5818631ba" ON "Meta_Geo_Water_Bodies" ("name") `);
        await queryRunner.query(`CREATE INDEX "IDX_603679fe3b2fe61026e40ff683" ON "Meta_Geo_Rivers" ("is_active") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_45e21d6a72e63d8e0f249bbf39" ON "Meta_Geo_Rivers" ("name") `);
        await queryRunner.query(`CREATE INDEX "IDX_6fed9764eca9a263e61e64f108" ON "Meta_Geo_Deserts" ("is_active") `);
        await queryRunner.query(`CREATE INDEX "IDX_3b1e427ac63835522ff5c43de3" ON "Meta_Geo_Countries" ("is_active") `);
        await queryRunner.query(`CREATE INDEX "IDX_dcc675fb08047c471b4586f04d" ON "Meta_Geo_Countries" ("dial_code") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_878a859c3a839a147600c5b6d8" ON "Meta_Geo_Countries" ("code_a3") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_e0730a0f54072c62ee1db7289e" ON "Meta_Geo_Countries" ("code_a2") `);
        await queryRunner.query(`CREATE INDEX "IDX_fb1541780676fa4a65deb2be35" ON "Meta_Geo_Continents" ("is_active") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_6f469e31117c95894c704439e4" ON "Meta_Geo_Continents" ("name") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_c3fae2f7847b5213ffbe1cb420" ON "Meta_Geo_Continents" ("code") `);
        await queryRunner.query(`CREATE INDEX "IDX_5a5d0b1f14fb947aa113e2bd9d" ON "Acd_Comparison_Items" ("is_active") `);
        await queryRunner.query(`CREATE INDEX "IDX_b9186fb1076d51cd39cb15fffd" ON "Acd_Comparisons" ("is_active") `);
        await queryRunner.query(`CREATE INDEX "IDX_afd2e3a74c2a30644f01bdd567" ON "Acd_Content_Comparisons" ("is_active") `);
        await queryRunner.query(`CREATE INDEX "IDX_0afdeeb26439230aaad1781b84" ON "Acd_Diagrams" ("is_active") `);
        await queryRunner.query(`CREATE INDEX "IDX_4d8eee0c7b3c262871bfa18fae" ON "Acd_Content_Diagrams" ("is_active") `);
        await queryRunner.query(`CREATE INDEX "IDX_560dc931b4dc9612e76f82d895" ON "Acd_Content" ("is_active") `);
        await queryRunner.query(`CREATE INDEX "IDX_0224d21448d8783d139eac78d0" ON "Acd_Syllabus" ("is_active") `);
        await queryRunner.query(`ALTER TABLE "App_Subscriptions" ADD CONSTRAINT "FK_f6a5238b4fd16e1d6bf898b6a7e" FOREIGN KEY ("plan_id") REFERENCES "App_Plans"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "App_Plans" ADD CONSTRAINT "FK_efb9f6680567e79829627588fa0" FOREIGN KEY ("node_id") REFERENCES "App_Nodes"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "App_Orders" ADD CONSTRAINT "FK_5627a665b2dbd39f68666da05b8" FOREIGN KEY ("plan_id") REFERENCES "App_Plans"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "App_Orders" DROP CONSTRAINT "FK_5627a665b2dbd39f68666da05b8"`);
        await queryRunner.query(`ALTER TABLE "App_Plans" DROP CONSTRAINT "FK_efb9f6680567e79829627588fa0"`);
        await queryRunner.query(`ALTER TABLE "App_Subscriptions" DROP CONSTRAINT "FK_f6a5238b4fd16e1d6bf898b6a7e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0224d21448d8783d139eac78d0"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_560dc931b4dc9612e76f82d895"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4d8eee0c7b3c262871bfa18fae"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0afdeeb26439230aaad1781b84"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_afd2e3a74c2a30644f01bdd567"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b9186fb1076d51cd39cb15fffd"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5a5d0b1f14fb947aa113e2bd9d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c3fae2f7847b5213ffbe1cb420"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6f469e31117c95894c704439e4"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_fb1541780676fa4a65deb2be35"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e0730a0f54072c62ee1db7289e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_878a859c3a839a147600c5b6d8"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_dcc675fb08047c471b4586f04d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3b1e427ac63835522ff5c43de3"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6fed9764eca9a263e61e64f108"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_45e21d6a72e63d8e0f249bbf39"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_603679fe3b2fe61026e40ff683"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b075f4336109e9bab5818631ba"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c5353e390a3d545087d02c929b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_752fbf19f9ef9241b729d51865"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3dafe8e504d69068a2e4028a57"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2498407c7c048a8143d41bc52f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ea7d09e61982b98a9920bdbc5e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_df1ac31e41efe8e985fdae0dbb"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d31d7ce68d9bf75a11d957f81a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1dd1db41c4a33bc92121e05fb7"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_156a9fed402cb96e877f4ca8e9"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_80f1763d5cfafc4a5193d89b1e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_27d3dfde29b373d2969098de75"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_73f288724f093c6cbe774fe5e9"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ad32f77582c45444d25ecaa683"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_35d298e0b7d4f5204017045752"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ea60f81fb3a3df93407a9dbe99"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ed2a5de64bf5f1719e13506b8e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_cefcb8861290ef1baaf964c409"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_feab35e90893152d0f6b3f0fbc"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_149d33f5b681601f1226a9cc29"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ff6502b8ebdc94a9a7a73e197b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_418897925b209bfd2b5807b29f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f5aff5920114252b7d12c0549e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_220f6ad9ab1e0e47f88b8d16f4"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_924b42905e2cd10ed5fa820042"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c3808f42fcaf7082d2ea37fda9"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ccc883b42da57062abb6520f5b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_555b924db8997f03ec49e416e4"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b237ff6093ab521eaf9ad50dac"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6278117936c7c8d2ed850a5394"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_17f330d29e4f9285a797f0fce8"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f4ba3cd398bf8188701139816a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f270a3832892a35339040fef36"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0cea8e3843fe84e3ca2d387dc0"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3656c9c243379c7573c4000404"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0d77c4c930691c477603bb006e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_17af54eb164f22204f7b6446a3"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f4a1fe1deebded3e06e3849c7d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_da2edacb664d1c9165ab9ecab4"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1f45e771a78e8e360c34d02a33"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_66f0b945db916893c35c8002a8"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_985af56efa4dc0a270541c789c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a61ea4effa78ec28c32898ecf8"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_64534a51882e89c399fb7f17a9"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9bb6c33098886ef04153a3f615"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_946e625be5e5b268ad2675ec09"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2b52ef874ff0a6b8698a409035"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b3463f4f4fc498924213c0fc1d"`);
        await queryRunner.query(`ALTER TABLE "Meta_Global_Orgs" ALTER COLUMN "primary_function" SET NOT NULL`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4c065ef3cc4a44f4327f3d043f"`);
        await queryRunner.query(`DROP TABLE "App_Plans"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a996499aa7897bb9715b7022f4"`);
        await queryRunner.query(`DROP TABLE "App_Nodes"`);
        await queryRunner.query(`CREATE INDEX "idx_acd_syllabus_is_active" ON "Acd_Syllabus" ("is_active") `);
        await queryRunner.query(`CREATE INDEX "idx_acd_content_is_active" ON "Acd_Content" ("is_active") `);
        await queryRunner.query(`CREATE INDEX "idx_acd_content_diagrams_is_active" ON "Acd_Content_Diagrams" ("is_active") `);
        await queryRunner.query(`CREATE INDEX "idx_acd_diagrams_is_active" ON "Acd_Diagrams" ("is_active") `);
        await queryRunner.query(`CREATE INDEX "idx_acd_content_comparisons_is_active" ON "Acd_Content_Comparisons" ("is_active") `);
        await queryRunner.query(`CREATE INDEX "idx_acd_comparisons_is_active" ON "Acd_Comparisons" ("is_active") `);
        await queryRunner.query(`CREATE INDEX "idx_acd_comparison_items_is_active" ON "Acd_Comparison_Items" ("is_active") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "idx_meta_geo_continents_code" ON "Meta_Geo_Continents" ("code") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "idx_meta_geo_continents_name" ON "Meta_Geo_Continents" ("name") `);
        await queryRunner.query(`CREATE INDEX "idx_meta_geo_continents_is_active" ON "Meta_Geo_Continents" ("is_active") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "idx_meta_geo_countries_code_a2" ON "Meta_Geo_Countries" ("code_a2") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "idx_meta_geo_countries_code_a3" ON "Meta_Geo_Countries" ("code_a3") `);
        await queryRunner.query(`CREATE INDEX "idx_meta_geo_countries_dial_code" ON "Meta_Geo_Countries" ("dial_code") `);
        await queryRunner.query(`CREATE INDEX "idx_meta_geo_countries_is_active" ON "Meta_Geo_Countries" ("is_active") `);
        await queryRunner.query(`CREATE INDEX "idx_meta_geo_deserts_is_active" ON "Meta_Geo_Deserts" ("is_active") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "idx_meta_geo_rivers_name" ON "Meta_Geo_Rivers" ("name") `);
        await queryRunner.query(`CREATE INDEX "idx_meta_geo_rivers_is_active" ON "Meta_Geo_Rivers" ("is_active") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "idx_meta_geo_water_bodies_name" ON "Meta_Geo_Water_Bodies" ("name") `);
        await queryRunner.query(`CREATE INDEX "idx_meta_geo_water_bodies_is_active" ON "Meta_Geo_Water_Bodies" ("is_active") `);
        await queryRunner.query(`CREATE INDEX "idx_meta_global_orgs_is_active" ON "Meta_Global_Orgs" ("is_active") `);
        await queryRunner.query(`CREATE INDEX "idx_app_clients_name" ON "App_Clients" ("name") `);
        await queryRunner.query(`CREATE INDEX "idx_app_clients_is_active" ON "App_Clients" ("is_active") `);
        await queryRunner.query(`CREATE INDEX "idx_app_users_email_is_active" ON "App_Users" ("email", "is_active") `);
        await queryRunner.query(`CREATE INDEX "idx_app_users_phone_is_active" ON "App_Users" ("is_active", "phone") `);
        await queryRunner.query(`CREATE INDEX "idx_app_users_phone" ON "App_Users" ("phone") `);
        await queryRunner.query(`CREATE INDEX "idx_app_users_email" ON "App_Users" ("email") `);
        await queryRunner.query(`CREATE INDEX "idx_app_users_is_active" ON "App_Users" ("is_active") `);
        await queryRunner.query(`CREATE INDEX "idx_auth_tokens_token" ON "Auth_Tokens" ("token") `);
        await queryRunner.query(`CREATE INDEX "idx_auth_tokens_type_token" ON "Auth_Tokens" ("token", "type") `);
        await queryRunner.query(`CREATE INDEX "idx_auth_tokens_user_id_type_is_revoked" ON "Auth_Tokens" ("is_revoked", "type", "user_id") `);
        await queryRunner.query(`CREATE INDEX "idx_auth_tokens_expires_at" ON "Auth_Tokens" ("expires_at") `);
        await queryRunner.query(`CREATE INDEX "idx_auth_tokens_user_id_type_expires_at" ON "Auth_Tokens" ("expires_at", "type", "user_id") `);
        await queryRunner.query(`CREATE INDEX "idx_auth_tokens_is_active" ON "Auth_Tokens" ("is_active") `);
        await queryRunner.query(`CREATE INDEX "idx_auth_sessions_is_active" ON "Auth_Sessions" ("is_active") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "idx_auth_provider_provider_provider_id" ON "Auth_Provider" ("provider", "provider_id") `);
        await queryRunner.query(`CREATE INDEX "idx_auth_provider_is_active" ON "Auth_Provider" ("is_active") `);
        await queryRunner.query(`CREATE INDEX "idx_auth_otps_user_id_channel_type_created_at" ON "Auth_Otps" ("channel", "created_at", "type", "user_id") `);
        await queryRunner.query(`CREATE INDEX "idx_auth_otps_user_id_channel_type_expires_at" ON "Auth_Otps" ("channel", "expires_at", "type", "user_id") `);
        await queryRunner.query(`CREATE INDEX "idx_auth_otps_is_active" ON "Auth_Otps" ("is_active") `);
        await queryRunner.query(`CREATE INDEX "idx_log_request_action" ON "Log_Request" ("action") `);
        await queryRunner.query(`CREATE INDEX "idx_log_request_device_id" ON "Log_Request" ("device_id") `);
        await queryRunner.query(`CREATE INDEX "idx_log_request_user_id" ON "Log_Request" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "idx_log_request_is_active" ON "Log_Request" ("is_active") `);
        await queryRunner.query(`CREATE INDEX "idx_log_response_status" ON "Log_Response" ("status") `);
        await queryRunner.query(`CREATE INDEX "idx_log_response_request_id" ON "Log_Response" ("request_id") `);
        await queryRunner.query(`CREATE INDEX "idx_log_response_is_active" ON "Log_Response" ("is_active") `);
        await queryRunner.query(`CREATE INDEX "idx_log_error_status" ON "Log_Error" ("status") `);
        await queryRunner.query(`CREATE INDEX "idx_log_error_is_active" ON "Log_Error" ("is_active") `);
        await queryRunner.query(`CREATE INDEX "idx_log_device_ip" ON "Log_Device" ("ip") `);
        await queryRunner.query(`CREATE INDEX "idx_log_device_is_active" ON "Log_Device" ("is_active") `);
        await queryRunner.query(`CREATE INDEX "idx_app_orders_is_active" ON "App_Orders" ("is_active") `);
        await queryRunner.query(`CREATE INDEX "idx_app_order_amounts_is_active" ON "App_Order_Amounts" ("is_active") `);
        await queryRunner.query(`CREATE INDEX "idx_app_subscriptions_is_active" ON "App_Subscriptions" ("is_active") `);
        await queryRunner.query(`CREATE INDEX "idx_app_payments_is_active" ON "App_Payments" ("is_active") `);
        await queryRunner.query(`CREATE INDEX "idx_app_payment_sessions_is_active" ON "App_Payment_Sessions" ("is_active") `);
        await queryRunner.query(`CREATE INDEX "idx_test_attempts_test_id" ON "Test_Attempts" ("test_id") `);
        await queryRunner.query(`CREATE INDEX "idx_test_attempts_user_id" ON "Test_Attempts" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "idx_test_attempts_is_active" ON "Test_Attempts" ("is_active") `);
        await queryRunner.query(`CREATE INDEX "idx_test_results_is_active" ON "Test_Results" ("is_active") `);
        await queryRunner.query(`CREATE INDEX "idx_test_questions_is_active" ON "Test_Questions" ("is_active") `);
        await queryRunner.query(`CREATE INDEX "idx_tests_title" ON "Tests" ("title") `);
        await queryRunner.query(`CREATE INDEX "idx_tests_is_active" ON "Tests" ("is_active") `);
        await queryRunner.query(`CREATE INDEX "idx_app_user_profiles_name" ON "App_User_Profiles" ("name") `);
        await queryRunner.query(`CREATE INDEX "idx_app_user_profiles_is_active" ON "App_User_Profiles" ("is_active") `);
        await queryRunner.query(`CREATE INDEX "idx_test_options_is_active" ON "Test_Options" ("is_active") `);
        await queryRunner.query(`ALTER TABLE "App_Orders" ADD CONSTRAINT "FK_5627a665b2dbd39f68666da05b8" FOREIGN KEY ("plan_id") REFERENCES "Meta_Plans"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "App_Subscriptions" ADD CONSTRAINT "FK_f6a5238b4fd16e1d6bf898b6a7e" FOREIGN KEY ("plan_id") REFERENCES "Meta_Plans"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
    }

}
