import { MigrationInterface, QueryRunner } from "typeorm";

export class AutoMigration1773469630542 implements MigrationInterface {
    name = 'AutoMigration1773469630542'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "Test_Options" ("id" SERIAL NOT NULL, "uid" character varying(12) NOT NULL, "is_active" boolean NOT NULL DEFAULT true, "created_by" integer NOT NULL DEFAULT '0', "created_at" TIMESTAMP WITH TIME ZONE NOT NULL, "updated_by" integer, "updated_at" TIMESTAMP WITH TIME ZONE, "expression" text NOT NULL, "is_correct" boolean NOT NULL DEFAULT false, "order" smallint NOT NULL, "question_id" integer, CONSTRAINT "UQ_c74f8187d55f73889e8157e3221" UNIQUE ("uid"), CONSTRAINT "PK_06fe1cd1c43b72dba03cb94537d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_b3463f4f4fc498924213c0fc1d" ON "Test_Options" ("is_active") `);
        await queryRunner.query(`CREATE TABLE "App_User_Profiles" ("id" SERIAL NOT NULL, "uid" character varying(12) NOT NULL, "is_active" boolean NOT NULL DEFAULT true, "created_by" integer NOT NULL DEFAULT '0', "created_at" TIMESTAMP WITH TIME ZONE NOT NULL, "updated_by" integer, "updated_at" TIMESTAMP WITH TIME ZONE, "name" character varying(50) NOT NULL, "grade" smallint NOT NULL, "topics" text array, "user_id" integer, CONSTRAINT "UQ_da7d01296f580dcc49aa3d8b927" UNIQUE ("uid"), CONSTRAINT "UQ_946e625be5e5b268ad2675ec097" UNIQUE ("name"), CONSTRAINT "PK_d1a84bee7d67c66569f5994b0ba" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_2b52ef874ff0a6b8698a409035" ON "App_User_Profiles" ("is_active") `);
        await queryRunner.query(`CREATE INDEX "IDX_946e625be5e5b268ad2675ec09" ON "App_User_Profiles" ("name") `);
        await queryRunner.query(`CREATE TABLE "Tests" ("id" SERIAL NOT NULL, "uid" character varying(12) NOT NULL, "is_active" boolean NOT NULL DEFAULT true, "created_by" integer NOT NULL DEFAULT '0', "created_at" TIMESTAMP WITH TIME ZONE NOT NULL, "updated_by" integer, "updated_at" TIMESTAMP WITH TIME ZONE, "title" text NOT NULL, "description" text, "difficulty_level" character(1), "score_mode" character(1) NOT NULL DEFAULT 'S', "total_questions" smallint NOT NULL DEFAULT '1', "points_per_question" smallint NOT NULL DEFAULT '1', "passing_points" smallint, "duration_mins" smallint NOT NULL DEFAULT '1', "is_published" boolean NOT NULL DEFAULT false, "publish_at" TIMESTAMP WITH TIME ZONE, "start_at" TIMESTAMP WITH TIME ZONE, "end_at" TIMESTAMP WITH TIME ZONE, "result_at" TIMESTAMP WITH TIME ZONE, "access_token" character(12), "max_attempts" smallint NOT NULL DEFAULT '1', "shuffle_questions" boolean NOT NULL DEFAULT false, "shuffle_options" boolean NOT NULL DEFAULT false, "show_result" boolean NOT NULL DEFAULT false, "show_answer" boolean NOT NULL DEFAULT false, "allow_pause" boolean NOT NULL DEFAULT false, "allow_tab_switch" smallint NOT NULL DEFAULT '0', "profile_id" integer, CONSTRAINT "UQ_f536604969fb21df8b719e1424e" UNIQUE ("uid"), CONSTRAINT "PK_c98b90a7239b78b3c48fcddd37d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_9bb6c33098886ef04153a3f615" ON "Tests" ("is_active") `);
        await queryRunner.query(`CREATE INDEX "IDX_64534a51882e89c399fb7f17a9" ON "Tests" ("title") `);
        await queryRunner.query(`CREATE TABLE "Test_Questions" ("id" SERIAL NOT NULL, "uid" character varying(12) NOT NULL, "is_active" boolean NOT NULL DEFAULT true, "created_by" integer NOT NULL DEFAULT '0', "created_at" TIMESTAMP WITH TIME ZONE NOT NULL, "updated_by" integer, "updated_at" TIMESTAMP WITH TIME ZONE, "difficulty_level" character(1), "topic" text, "expression" text NOT NULL, "type" smallint NOT NULL DEFAULT '1', "order" smallint, "points" smallint NOT NULL DEFAULT '1', "test_id" integer, CONSTRAINT "UQ_e770fd1bf8d9520a464f1916a69" UNIQUE ("uid"), CONSTRAINT "PK_a613a5f1d56e89ee37e0f493197" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_a61ea4effa78ec28c32898ecf8" ON "Test_Questions" ("is_active") `);
        await queryRunner.query(`CREATE TABLE "Test_Results" ("id" SERIAL NOT NULL, "uid" character varying(12) NOT NULL, "is_active" boolean NOT NULL DEFAULT true, "created_by" integer NOT NULL DEFAULT '0', "created_at" TIMESTAMP WITH TIME ZONE NOT NULL, "updated_by" integer, "updated_at" TIMESTAMP WITH TIME ZONE, "selected_options" jsonb, "is_correct" boolean NOT NULL DEFAULT false, "attempt_id" integer, "question_id" integer, CONSTRAINT "UQ_f02470dc6a3803d74d69a2e7ba3" UNIQUE ("uid"), CONSTRAINT "PK_13aaa09ce13af9798a4dcc956c1" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_985af56efa4dc0a270541c789c" ON "Test_Results" ("is_active") `);
        await queryRunner.query(`CREATE TABLE "Test_Attempts" ("id" SERIAL NOT NULL, "uid" character varying(12) NOT NULL, "is_active" boolean NOT NULL DEFAULT true, "created_by" integer NOT NULL DEFAULT '0', "created_at" TIMESTAMP WITH TIME ZONE NOT NULL, "updated_by" integer, "updated_at" TIMESTAMP WITH TIME ZONE, "start_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "submit_at" TIMESTAMP WITH TIME ZONE, "is_auto_submit" boolean NOT NULL DEFAULT false, "score" smallint NOT NULL DEFAULT '0', "attempt_count" smallint NOT NULL DEFAULT '1', "tab_switch_count" smallint NOT NULL DEFAULT '0', "user_id" integer, "test_id" integer, CONSTRAINT "UQ_c5cd1f4db6f7207ff1c7871ccfa" UNIQUE ("uid"), CONSTRAINT "PK_ab02a01202defe0d676c8240ee1" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_66f0b945db916893c35c8002a8" ON "Test_Attempts" ("is_active") `);
        await queryRunner.query(`CREATE INDEX "IDX_1f45e771a78e8e360c34d02a33" ON "Test_Attempts" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_da2edacb664d1c9165ab9ecab4" ON "Test_Attempts" ("test_id") `);
        await queryRunner.query(`CREATE TABLE "Log_Device" ("id" SERIAL NOT NULL, "uid" character varying(12) NOT NULL, "is_active" boolean NOT NULL DEFAULT true, "created_by" integer NOT NULL DEFAULT '0', "created_at" TIMESTAMP WITH TIME ZONE NOT NULL, "ip" character varying(45) NOT NULL, "timezone" text NOT NULL, "geo" text, "agent" text, CONSTRAINT "UQ_60205bd4080ff5a7fcec1dff9d5" UNIQUE ("uid"), CONSTRAINT "PK_b5edee526074292dfd1974e4994" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_f270a3832892a35339040fef36" ON "Log_Device" ("is_active") `);
        await queryRunner.query(`CREATE INDEX "IDX_f4ba3cd398bf8188701139816a" ON "Log_Device" ("ip") `);
        await queryRunner.query(`CREATE TABLE "Log_Error" ("id" SERIAL NOT NULL, "uid" character varying(12) NOT NULL, "is_active" boolean NOT NULL DEFAULT true, "created_by" integer NOT NULL DEFAULT '0', "created_at" TIMESTAMP WITH TIME ZONE NOT NULL, "status" smallint NOT NULL, "name" text, "message" text, "source" text, "request_id" integer, CONSTRAINT "UQ_76caa3956d40e4ec00e32fe623c" UNIQUE ("uid"), CONSTRAINT "PK_bad4884a10d45ab182d2f06a0a9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_17f330d29e4f9285a797f0fce8" ON "Log_Error" ("is_active") `);
        await queryRunner.query(`CREATE INDEX "IDX_6278117936c7c8d2ed850a5394" ON "Log_Error" ("status") `);
        await queryRunner.query(`CREATE TABLE "Log_Response" ("id" SERIAL NOT NULL, "uid" character varying(12) NOT NULL, "is_active" boolean NOT NULL DEFAULT true, "created_by" integer NOT NULL DEFAULT '0', "created_at" TIMESTAMP WITH TIME ZONE NOT NULL, "status" smallint NOT NULL, "message" text, "duration_ms" integer, "request_id" integer, CONSTRAINT "UQ_3426c57d602ff62c638ae00bca6" UNIQUE ("uid"), CONSTRAINT "PK_d7b22fb299e03be92ae2b84af91" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_b237ff6093ab521eaf9ad50dac" ON "Log_Response" ("is_active") `);
        await queryRunner.query(`CREATE INDEX "IDX_555b924db8997f03ec49e416e4" ON "Log_Response" ("request_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_ccc883b42da57062abb6520f5b" ON "Log_Response" ("status") `);
        await queryRunner.query(`CREATE TABLE "Log_Request" ("id" SERIAL NOT NULL, "uid" character varying(12) NOT NULL, "is_active" boolean NOT NULL DEFAULT true, "created_by" integer NOT NULL DEFAULT '0', "created_at" TIMESTAMP WITH TIME ZONE NOT NULL, "action" text NOT NULL, "payload" jsonb, "user_id" integer, "device_id" integer, CONSTRAINT "UQ_2e1fe8fb32a4d715c7438ab1028" UNIQUE ("uid"), CONSTRAINT "PK_4b3e54fa14fa24b0b9a36e7bc7a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_c3808f42fcaf7082d2ea37fda9" ON "Log_Request" ("is_active") `);
        await queryRunner.query(`CREATE INDEX "IDX_924b42905e2cd10ed5fa820042" ON "Log_Request" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_220f6ad9ab1e0e47f88b8d16f4" ON "Log_Request" ("device_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_f5aff5920114252b7d12c0549e" ON "Log_Request" ("action") `);
        await queryRunner.query(`CREATE TABLE "App_Payment_Sessions" ("id" SERIAL NOT NULL, "uid" character varying(12) NOT NULL, "is_active" boolean NOT NULL DEFAULT true, "created_by" integer NOT NULL DEFAULT '0', "created_at" TIMESTAMP WITH TIME ZONE NOT NULL, "provider" character varying(50) NOT NULL, "status" character(4) NOT NULL DEFAULT 'PEND', "payment_id" integer, CONSTRAINT "UQ_a6e7527d7d544c034c434be6b2f" UNIQUE ("uid"), CONSTRAINT "PK_a54407013612709250bb34d945a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_f4a1fe1deebded3e06e3849c7d" ON "App_Payment_Sessions" ("is_active") `);
        await queryRunner.query(`CREATE TABLE "App_Payments" ("id" SERIAL NOT NULL, "uid" character varying(12) NOT NULL, "is_active" boolean NOT NULL DEFAULT true, "created_by" integer NOT NULL DEFAULT '0', "created_at" TIMESTAMP WITH TIME ZONE NOT NULL, "updated_by" integer, "updated_at" TIMESTAMP WITH TIME ZONE, "status" character(4) NOT NULL DEFAULT 'PEND', "method" character(3) NOT NULL, "amount" numeric(12,2) NOT NULL, "currency" character(3) NOT NULL, "user_id" integer, "order_id" integer, CONSTRAINT "UQ_53a5cf6b58bdc1bdb48093fc09e" UNIQUE ("uid"), CONSTRAINT "PK_9556ef337d49bf24dddae5db9d6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_17af54eb164f22204f7b6446a3" ON "App_Payments" ("is_active") `);
        await queryRunner.query(`CREATE TABLE "App_Subscriptions" ("id" SERIAL NOT NULL, "uid" character varying(12) NOT NULL, "is_active" boolean NOT NULL DEFAULT true, "created_by" integer NOT NULL DEFAULT '0', "created_at" TIMESTAMP WITH TIME ZONE NOT NULL, "updated_by" integer, "updated_at" TIMESTAMP WITH TIME ZONE, "status" character(3) NOT NULL DEFAULT 'ACT', "start_date" TIMESTAMP WITH TIME ZONE NOT NULL, "end_date" TIMESTAMP WITH TIME ZONE NOT NULL, "user_id" integer, "plan_id" integer, "order_id" integer, "payment_id" integer, CONSTRAINT "UQ_e5edac899bc934a2eebe22ba56d" UNIQUE ("uid"), CONSTRAINT "REL_3e3a004a337da6b08042b5e9fe" UNIQUE ("payment_id"), CONSTRAINT "PK_f3d5fa342f2f5219dea1c900c92" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_0d77c4c930691c477603bb006e" ON "App_Subscriptions" ("is_active") `);
        await queryRunner.query(`CREATE TABLE "App_Nodes" ("id" SERIAL NOT NULL, "uid" character varying(12) NOT NULL, "is_active" boolean NOT NULL DEFAULT true, "created_by" integer NOT NULL DEFAULT '0', "created_at" TIMESTAMP WITH TIME ZONE NOT NULL, "master" character(1) NOT NULL, "order" smallint NOT NULL DEFAULT '0', "label" character varying(50) NOT NULL, "avatar" character varying(50), "description" character varying(255), "description_long" character varying(511), "protected" boolean NOT NULL DEFAULT false, "meta" text array, CONSTRAINT "UQ_bd77c4905baae2a5e6eecde9c6b" UNIQUE ("uid"), CONSTRAINT "PK_62328f7ef09c4e0160a48b06006" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_a996499aa7897bb9715b7022f4" ON "App_Nodes" ("is_active") `);
        await queryRunner.query(`CREATE TABLE "App_Plans" ("id" SERIAL NOT NULL, "uid" character varying(12) NOT NULL, "is_active" boolean NOT NULL DEFAULT true, "created_by" integer NOT NULL DEFAULT '0', "created_at" TIMESTAMP WITH TIME ZONE NOT NULL, "type" character(1) NOT NULL, "bill_mode" character(1) NOT NULL, "currency" character(3) NOT NULL DEFAULT 'INR', "actual_price" numeric(8,2), "discount_price" numeric(8,2), "discount_rate" numeric(5,2), "node_id" integer NOT NULL, CONSTRAINT "UQ_a6427ba5df63f9cf3c6b4beee45" UNIQUE ("uid"), CONSTRAINT "PK_a22ec10022cb17bdd44e42c2efa" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_4c065ef3cc4a44f4327f3d043f" ON "App_Plans" ("is_active") `);
        await queryRunner.query(`CREATE TABLE "App_Order_Amounts" ("id" SERIAL NOT NULL, "uid" character varying(12) NOT NULL, "is_active" boolean NOT NULL DEFAULT true, "created_by" integer NOT NULL DEFAULT '0', "created_at" TIMESTAMP WITH TIME ZONE NOT NULL, "type" character varying(10) NOT NULL, "amount" numeric(8,2) NOT NULL, "remark" character varying(50), "order_id" integer, CONSTRAINT "UQ_aeb061f51f1b4d20d78c27ff8ad" UNIQUE ("uid"), CONSTRAINT "PK_e4833dc25921fd65939ab872b99" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_3656c9c243379c7573c4000404" ON "App_Order_Amounts" ("is_active") `);
        await queryRunner.query(`CREATE TABLE "App_Orders" ("id" SERIAL NOT NULL, "uid" character varying(12) NOT NULL, "is_active" boolean NOT NULL DEFAULT true, "created_by" integer NOT NULL DEFAULT '0', "created_at" TIMESTAMP WITH TIME ZONE NOT NULL, "updated_by" integer, "updated_at" TIMESTAMP WITH TIME ZONE, "status" character(4) NOT NULL DEFAULT 'PEND', "currency" character(3) NOT NULL, "user_id" integer, "plan_id" integer, CONSTRAINT "UQ_bebf849ef65ab084e3d22ae3bc8" UNIQUE ("uid"), CONSTRAINT "PK_2545bf7ccb826a3b250effe28d1" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_0cea8e3843fe84e3ca2d387dc0" ON "App_Orders" ("is_active") `);
        await queryRunner.query(`CREATE TABLE "Auth_Otps" ("id" SERIAL NOT NULL, "uid" character varying(12) NOT NULL, "is_active" boolean NOT NULL DEFAULT true, "created_by" integer NOT NULL DEFAULT '0', "created_at" TIMESTAMP WITH TIME ZONE NOT NULL, "updated_by" integer, "updated_at" TIMESTAMP WITH TIME ZONE, "channel" character(1) NOT NULL, "type" character(1) NOT NULL, "otp" character varying(100) NOT NULL, "is_revoked" boolean NOT NULL DEFAULT false, "expires_sec" integer NOT NULL, "expires_at" TIMESTAMP WITH TIME ZONE NOT NULL, "user_id" integer, CONSTRAINT "UQ_54a01218136600c8291f8ce338f" UNIQUE ("uid"), CONSTRAINT "PK_8e4317638967bd16501ae056fb4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_418897925b209bfd2b5807b29f" ON "Auth_Otps" ("is_active") `);
        await queryRunner.query(`CREATE INDEX "IDX_ff6502b8ebdc94a9a7a73e197b" ON "Auth_Otps" ("user_id", "channel", "type", "expires_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_149d33f5b681601f1226a9cc29" ON "Auth_Otps" ("user_id", "channel", "type", "created_at") `);
        await queryRunner.query(`CREATE TABLE "Auth_Provider" ("id" SERIAL NOT NULL, "uid" character varying(12) NOT NULL, "is_active" boolean NOT NULL DEFAULT true, "created_by" integer NOT NULL DEFAULT '0', "created_at" TIMESTAMP WITH TIME ZONE NOT NULL, "provider" character(1) NOT NULL, "provider_id" character varying(100) NOT NULL, "user_id" integer NOT NULL, CONSTRAINT "UQ_562c25d65529d8b0741457ec2a9" UNIQUE ("uid"), CONSTRAINT "PK_c5c1e54a9af43328d86f75e2948" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_feab35e90893152d0f6b3f0fbc" ON "Auth_Provider" ("is_active") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_cefcb8861290ef1baaf964c409" ON "Auth_Provider" ("provider", "provider_id") `);
        await queryRunner.query(`CREATE TABLE "Auth_Sessions" ("id" SERIAL NOT NULL, "uid" character varying(12) NOT NULL, "is_active" boolean NOT NULL DEFAULT true, "created_by" integer NOT NULL DEFAULT '0', "created_at" TIMESTAMP WITH TIME ZONE NOT NULL, "updated_by" integer, "updated_at" TIMESTAMP WITH TIME ZONE, "failed_logins" integer NOT NULL DEFAULT '0', "last_failed_login_at" TIMESTAMP WITH TIME ZONE, "last_success_login_at" TIMESTAMP WITH TIME ZONE, "lockout_until" TIMESTAMP WITH TIME ZONE, "is_suspended" boolean NOT NULL DEFAULT false, "max_active" integer NOT NULL DEFAULT '5', "user_id" integer, CONSTRAINT "UQ_7a4e15958e847b551fd94dbd0c1" UNIQUE ("uid"), CONSTRAINT "REL_24ac36e83804ccbeb26ace1cec" UNIQUE ("user_id"), CONSTRAINT "PK_ccc2dfbccf3a7d2afa8da28b2d0" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_ed2a5de64bf5f1719e13506b8e" ON "Auth_Sessions" ("is_active") `);
        await queryRunner.query(`CREATE TABLE "Auth_Tokens" ("id" SERIAL NOT NULL, "uid" character varying(12) NOT NULL, "is_active" boolean NOT NULL DEFAULT true, "created_by" integer NOT NULL DEFAULT '0', "created_at" TIMESTAMP WITH TIME ZONE NOT NULL, "updated_by" integer, "updated_at" TIMESTAMP WITH TIME ZONE, "type" character(1) NOT NULL, "token" character varying(255) NOT NULL, "is_revoked" boolean NOT NULL DEFAULT false, "expires_sec" integer NOT NULL, "expires_at" TIMESTAMP WITH TIME ZONE NOT NULL, "user_id" integer, CONSTRAINT "UQ_f5e454205b8dc0e8c8a255b30a3" UNIQUE ("uid"), CONSTRAINT "PK_9246abeee5c6d4233e0c651ca23" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_ea60f81fb3a3df93407a9dbe99" ON "Auth_Tokens" ("is_active") `);
        await queryRunner.query(`CREATE INDEX "IDX_35d298e0b7d4f5204017045752" ON "Auth_Tokens" ("user_id", "type", "expires_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_ad32f77582c45444d25ecaa683" ON "Auth_Tokens" ("expires_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_73f288724f093c6cbe774fe5e9" ON "Auth_Tokens" ("user_id", "type", "is_revoked") `);
        await queryRunner.query(`CREATE INDEX "IDX_27d3dfde29b373d2969098de75" ON "Auth_Tokens" ("type", "token") `);
        await queryRunner.query(`CREATE INDEX "IDX_80f1763d5cfafc4a5193d89b1e" ON "Auth_Tokens" ("token") `);
        await queryRunner.query(`CREATE TABLE "App_Users" ("id" SERIAL NOT NULL, "uid" character varying(12) NOT NULL, "is_active" boolean NOT NULL DEFAULT true, "created_by" integer NOT NULL DEFAULT '0', "created_at" TIMESTAMP WITH TIME ZONE NOT NULL, "updated_by" integer, "updated_at" TIMESTAMP WITH TIME ZONE, "is_internal" boolean NOT NULL DEFAULT false, "email" character varying(50), "phone" character varying(15), "first_name" character varying(50), "last_name" character varying(50), "avatar" character varying(50), "password" text, "password_changed_at" TIMESTAMP WITH TIME ZONE, "is_email_verified" boolean NOT NULL DEFAULT false, "is_phone_verified" boolean NOT NULL DEFAULT false, "role" smallint NOT NULL DEFAULT '4', CONSTRAINT "UQ_30af6d8b2fad37643dd1dae9613" UNIQUE ("uid"), CONSTRAINT "UQ_1dd1db41c4a33bc92121e05fb73" UNIQUE ("email"), CONSTRAINT "CHK_6d544d397ff3993c829da79960" CHECK ("email" IS NOT NULL OR "phone" IS NOT NULL), CONSTRAINT "PK_fd7a5c85dbc5419fd6b25ffa6e2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_156a9fed402cb96e877f4ca8e9" ON "App_Users" ("is_active") `);
        await queryRunner.query(`CREATE INDEX "IDX_1dd1db41c4a33bc92121e05fb7" ON "App_Users" ("email") `);
        await queryRunner.query(`CREATE INDEX "IDX_d31d7ce68d9bf75a11d957f81a" ON "App_Users" ("phone") `);
        await queryRunner.query(`CREATE INDEX "IDX_df1ac31e41efe8e985fdae0dbb" ON "App_Users" ("phone", "is_active") `);
        await queryRunner.query(`CREATE INDEX "IDX_ea7d09e61982b98a9920bdbc5e" ON "App_Users" ("email", "is_active") `);
        await queryRunner.query(`CREATE TABLE "App_Clients" ("id" SERIAL NOT NULL, "uid" character varying(12) NOT NULL, "is_active" boolean NOT NULL DEFAULT true, "created_by" integer NOT NULL DEFAULT '0', "created_at" TIMESTAMP WITH TIME ZONE NOT NULL, "updated_by" integer, "updated_at" TIMESTAMP WITH TIME ZONE, "name" character varying(63) NOT NULL, "ip_from" character varying(40) NOT NULL, "ip_to" character varying(40), "origins" character varying(255), "rate_limit" smallint NOT NULL DEFAULT '3', CONSTRAINT "UQ_4c62934ecb8e8e3fca6d886ae26" UNIQUE ("uid"), CONSTRAINT "UQ_3dafe8e504d69068a2e4028a578" UNIQUE ("name"), CONSTRAINT "PK_b4deaa2abe46f5cc64f014ed69a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_2498407c7c048a8143d41bc52f" ON "App_Clients" ("is_active") `);
        await queryRunner.query(`CREATE INDEX "IDX_3dafe8e504d69068a2e4028a57" ON "App_Clients" ("name") `);
        await queryRunner.query(`CREATE TABLE "Meta_Global_Orgs" ("id" SERIAL NOT NULL, "uid" character varying(12) NOT NULL, "is_active" boolean NOT NULL DEFAULT true, "created_by" integer NOT NULL DEFAULT '0', "created_at" TIMESTAMP WITH TIME ZONE NOT NULL, "abbr" character varying(50), "name" character varying(255) NOT NULL, "official_name" text, "former_name" text, "alt_names" text, "establish_era" character(1), "status" character(1), "dissolve_year" integer, "found_year" integer, "found_date" date, "found_place" character varying(255), "headquarters_city" character varying(150), "headquarters_country" character(2), "type" character(1), "category" character(1), "scope" character(1), "member_count" integer, "member_type" character(1), "member_detail" character(1), "member_permanent" integer, "leader_title" character(1), "primary_function" text, "secondary_functions" text, "key_objectives" text, "famous_for" text, "is_un_body" boolean NOT NULL DEFAULT false, "parent_org" character varying(255), "affiliated_org" text, "official_language" character varying(150), "website" character varying(255), "logo_url" character varying(500), "decision_making_body" character varying(150), "remark" text, CONSTRAINT "UQ_86062f42c76158a6d07906d72d0" UNIQUE ("uid"), CONSTRAINT "PK_2e9a386cad17d1f9355941b7372" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_752fbf19f9ef9241b729d51865" ON "Meta_Global_Orgs" ("is_active") `);
        await queryRunner.query(`CREATE TABLE "Meta_Geo_Water_Bodies" ("id" SERIAL NOT NULL, "uid" character varying(12) NOT NULL, "is_active" boolean NOT NULL DEFAULT true, "created_by" integer NOT NULL DEFAULT '0', "created_at" TIMESTAMP WITH TIME ZONE NOT NULL, "type" character(1) NOT NULL, "name" character varying(100) NOT NULL, "iso_code" character varying(10), "drinkable" boolean NOT NULL DEFAULT false, "seasonally_frozen" boolean, "temperature" character(1), "salinity" character(1), "color" character(1), "clarity" character(1), "coastal_type" character(1), "oxygen_level" character(1), "rank_area" smallint, "rank_depth" smallint, "area_km2" integer, "max_depth_m" integer, "deepest_point" character varying(100), "avg_temp_c" smallint, "ocean" character varying(50), "continents" character(2) array, "countries" character(2) array, "description" text, CONSTRAINT "UQ_743d9e832040dc77afb75fffb05" UNIQUE ("uid"), CONSTRAINT "PK_90ffe4d67954f1657746822c17d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_c5353e390a3d545087d02c929b" ON "Meta_Geo_Water_Bodies" ("is_active") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_b075f4336109e9bab5818631ba" ON "Meta_Geo_Water_Bodies" ("name") `);
        await queryRunner.query(`CREATE TABLE "Meta_Geo_Rivers" ("id" SERIAL NOT NULL, "uid" character varying(12) NOT NULL, "is_active" boolean NOT NULL DEFAULT true, "created_by" integer NOT NULL DEFAULT '0', "created_at" TIMESTAMP WITH TIME ZONE NOT NULL, "name" character varying(100) NOT NULL, "iso_code" character(10), "length_km" integer, "discharge_m3s" integer, "basin_area_km2" integer, "rank_length" smallint, "rank_discharge" smallint, "source" character varying(100), "mouth" character varying(100), "continent" character varying(50), "countries" character(2) array, CONSTRAINT "UQ_701aa9eac72849735d4560188d6" UNIQUE ("uid"), CONSTRAINT "PK_6d19113d219f8fb7c96b0096d3b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_603679fe3b2fe61026e40ff683" ON "Meta_Geo_Rivers" ("is_active") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_45e21d6a72e63d8e0f249bbf39" ON "Meta_Geo_Rivers" ("name") `);
        await queryRunner.query(`CREATE TABLE "Meta_Geo_Deserts" ("id" SERIAL NOT NULL, "uid" character varying(12) NOT NULL, "is_active" boolean NOT NULL DEFAULT true, "created_by" integer NOT NULL DEFAULT '0', "created_at" TIMESTAMP WITH TIME ZONE NOT NULL, "rank" smallint NOT NULL, "name" character varying(100) NOT NULL, "area_km2" bigint NOT NULL, "type" character varying(20) NOT NULL, "continent" character(2) NOT NULL, "countries" text array NOT NULL, CONSTRAINT "UQ_9f2ad82573d6a2c79ea2f9f9cc4" UNIQUE ("uid"), CONSTRAINT "UQ_4f18f63df6893cbba3df10548e6" UNIQUE ("rank"), CONSTRAINT "PK_6751f76cc33f2ffc597b0e6793e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_6fed9764eca9a263e61e64f108" ON "Meta_Geo_Deserts" ("is_active") `);
        await queryRunner.query(`CREATE TABLE "Meta_Geo_Countries" ("id" SERIAL NOT NULL, "uid" character varying(12) NOT NULL, "is_active" boolean NOT NULL DEFAULT true, "created_by" integer NOT NULL DEFAULT '0', "created_at" TIMESTAMP WITH TIME ZONE NOT NULL, "continent" character(2) NOT NULL, "name" character varying(100) NOT NULL, "capital" character varying(100) NOT NULL, "code_a2" character(2) NOT NULL, "code_a3" character(3) NOT NULL, "internet_tld" character(3) NOT NULL, "dial_code" character varying(15) NOT NULL, "cur_code" character(3) NOT NULL, "cur_name" character varying(50) NOT NULL, "cur_symbol" character varying(5), "olympic_code" character varying(100), "largest_city" character varying(100), "highest_point" character varying(100), "longest_river" character varying(100), "national_bank_abbr" character varying(10), "national_bank_name" character varying(100), "national_sport" character varying(100), "national_animal" character varying(100), "national_bird" character varying(100), "national_flower" character varying(100), "national_anthem" character varying(100), "official_language" character varying(100), "religions" character varying(100), "flag_url" character(12) NOT NULL, "flag_description" character varying(100), "time_zones" character varying(100) NOT NULL, "latitude" numeric(9,6), "longitude" numeric(9,6), "global_orgs" character varying(100), "is_landlocked" boolean, "is_island" boolean, "has_desert" boolean, "has_rainforest" boolean, "rank_area" smallint, "neighbor_countries" character varying(50), "independence_date" character(10), "former_name" character varying(100), CONSTRAINT "UQ_dcfd02bbf1d2680a4684b92d931" UNIQUE ("uid"), CONSTRAINT "PK_de795f3d48cdab5e831be8fdedc" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_3b1e427ac63835522ff5c43de3" ON "Meta_Geo_Countries" ("is_active") `);
        await queryRunner.query(`CREATE INDEX "IDX_dcc675fb08047c471b4586f04d" ON "Meta_Geo_Countries" ("dial_code") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_878a859c3a839a147600c5b6d8" ON "Meta_Geo_Countries" ("code_a3") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_e0730a0f54072c62ee1db7289e" ON "Meta_Geo_Countries" ("code_a2") `);
        await queryRunner.query(`CREATE TABLE "Meta_Geo_Continents" ("id" SERIAL NOT NULL, "uid" character varying(12) NOT NULL, "is_active" boolean NOT NULL DEFAULT true, "created_by" integer NOT NULL DEFAULT '0', "created_at" TIMESTAMP WITH TIME ZONE NOT NULL, "code" character varying(5) NOT NULL, "name" character varying(50) NOT NULL, "region_group" character varying(50), "country_count" smallint, "rank_population" smallint, "rank_area" smallint, "rank_density" smallint, "rank_country_count" smallint, "largest_country" character(2), "smallest_country" character(2), "highest_mountain" character varying(100), "longest_river" character varying(100), "largest_desert" character varying(100), CONSTRAINT "UQ_2e451e6b3a638118c99214f35ef" UNIQUE ("uid"), CONSTRAINT "UQ_c3fae2f7847b5213ffbe1cb4209" UNIQUE ("code"), CONSTRAINT "UQ_6f469e31117c95894c704439e47" UNIQUE ("name"), CONSTRAINT "PK_9bd1ed28f97ee63003d405b9a89" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_fb1541780676fa4a65deb2be35" ON "Meta_Geo_Continents" ("is_active") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_6f469e31117c95894c704439e4" ON "Meta_Geo_Continents" ("name") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_c3fae2f7847b5213ffbe1cb420" ON "Meta_Geo_Continents" ("code") `);
        await queryRunner.query(`CREATE TABLE "Acd_Comparison_Items" ("id" SERIAL NOT NULL, "uid" character varying(12) NOT NULL, "is_active" boolean NOT NULL DEFAULT true, "created_by" integer NOT NULL DEFAULT '0', "created_at" TIMESTAMP WITH TIME ZONE NOT NULL, "updated_by" integer, "updated_at" TIMESTAMP WITH TIME ZONE, "order_row" integer NOT NULL DEFAULT '0', "order_col" integer NOT NULL DEFAULT '0', "content" character varying(500) NOT NULL, "comparison_id" integer, CONSTRAINT "UQ_b6d1bb01598e718bde6b7f7a383" UNIQUE ("uid"), CONSTRAINT "PK_ae55cf92ac0f09a2182b31fa989" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_5a5d0b1f14fb947aa113e2bd9d" ON "Acd_Comparison_Items" ("is_active") `);
        await queryRunner.query(`CREATE TABLE "Acd_Comparisons" ("id" SERIAL NOT NULL, "uid" character varying(12) NOT NULL, "is_active" boolean NOT NULL DEFAULT true, "created_by" integer NOT NULL DEFAULT '0', "created_at" TIMESTAMP WITH TIME ZONE NOT NULL, "updated_by" integer, "updated_at" TIMESTAMP WITH TIME ZONE, "title" character varying(120) NOT NULL, "topics" character varying(120) NOT NULL, CONSTRAINT "UQ_e6748b012355aa49a041dd0e79b" UNIQUE ("uid"), CONSTRAINT "PK_3611438703b1c5f564132f9d53b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_b9186fb1076d51cd39cb15fffd" ON "Acd_Comparisons" ("is_active") `);
        await queryRunner.query(`CREATE TABLE "Acd_Content_Comparisons" ("id" SERIAL NOT NULL, "uid" character varying(12) NOT NULL, "is_active" boolean NOT NULL DEFAULT true, "created_by" integer NOT NULL DEFAULT '0', "created_at" TIMESTAMP WITH TIME ZONE NOT NULL, "updated_by" integer, "updated_at" TIMESTAMP WITH TIME ZONE, "order" integer NOT NULL DEFAULT '0', "content_id" integer, "comparison_id" integer, CONSTRAINT "UQ_beefe4ec80722a9996937f696f3" UNIQUE ("uid"), CONSTRAINT "PK_ebd63f753e928a31b648b892126" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_afd2e3a74c2a30644f01bdd567" ON "Acd_Content_Comparisons" ("is_active") `);
        await queryRunner.query(`CREATE TYPE "public"."Acd_Diagrams_media_enum" AS ENUM('I', 'S', 'V')`);
        await queryRunner.query(`CREATE TABLE "Acd_Diagrams" ("id" SERIAL NOT NULL, "uid" character varying(12) NOT NULL, "is_active" boolean NOT NULL DEFAULT true, "created_by" integer NOT NULL DEFAULT '0', "created_at" TIMESTAMP WITH TIME ZONE NOT NULL, "updated_by" integer, "updated_at" TIMESTAMP WITH TIME ZONE, "media" "public"."Acd_Diagrams_media_enum" NOT NULL, "title" character varying(120) NOT NULL, "url" character varying(120) NOT NULL, CONSTRAINT "UQ_c79b1137b9658c12fb390ebcb5a" UNIQUE ("uid"), CONSTRAINT "PK_b183e5d2e3f87a2ddf008ad1bce" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_0afdeeb26439230aaad1781b84" ON "Acd_Diagrams" ("is_active") `);
        await queryRunner.query(`CREATE TABLE "Acd_Content_Diagrams" ("id" SERIAL NOT NULL, "uid" character varying(12) NOT NULL, "is_active" boolean NOT NULL DEFAULT true, "created_by" integer NOT NULL DEFAULT '0', "created_at" TIMESTAMP WITH TIME ZONE NOT NULL, "updated_by" integer, "updated_at" TIMESTAMP WITH TIME ZONE, "order" integer NOT NULL DEFAULT '0', "content_id" integer, "diagram_id" integer, CONSTRAINT "UQ_e427ef929bf5db597d916f87cfc" UNIQUE ("uid"), CONSTRAINT "PK_8ea21eaaeea9775aec4bf294f04" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_4d8eee0c7b3c262871bfa18fae" ON "Acd_Content_Diagrams" ("is_active") `);
        await queryRunner.query(`CREATE TABLE "Acd_Content" ("id" SERIAL NOT NULL, "uid" character varying(12) NOT NULL, "is_active" boolean NOT NULL DEFAULT true, "created_by" integer NOT NULL DEFAULT '0', "created_at" TIMESTAMP WITH TIME ZONE NOT NULL, "updated_by" integer, "updated_at" TIMESTAMP WITH TIME ZONE, "order" integer NOT NULL DEFAULT '0', "type" character(1) NOT NULL, "title" character varying(120) NOT NULL, "content" character varying(500) NOT NULL, "topic_id" integer, CONSTRAINT "UQ_dc58c2b902f2e27816d5c696c33" UNIQUE ("uid"), CONSTRAINT "PK_2fa12592c61f4b1b275d3865dbf" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_560dc931b4dc9612e76f82d895" ON "Acd_Content" ("is_active") `);
        await queryRunner.query(`CREATE TABLE "Acd_Syllabus" ("id" SERIAL NOT NULL, "uid" character varying(12) NOT NULL, "is_active" boolean NOT NULL DEFAULT true, "created_by" integer NOT NULL DEFAULT '0', "created_at" TIMESTAMP WITH TIME ZONE NOT NULL, "code" character varying(9), "label" character varying(50) NOT NULL, "grade_from" smallint NOT NULL, "grade_to" smallint NOT NULL, "order" smallint NOT NULL, "level" smallint NOT NULL DEFAULT '0', "description" character varying(255), "avatar" character varying(50), "enable_sheets" boolean NOT NULL DEFAULT true, "enable_games" boolean NOT NULL DEFAULT true, "enable_tests" boolean NOT NULL DEFAULT true, "enable_boards" boolean NOT NULL DEFAULT true, "enable_notes" boolean NOT NULL DEFAULT true, "parent_id" integer, CONSTRAINT "UQ_fa88762071530b06f28e1b1a661" UNIQUE ("uid"), CONSTRAINT "PK_60d7bc42cd1e11f52a8fddcf67d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_0224d21448d8783d139eac78d0" ON "Acd_Syllabus" ("is_active") `);
        await queryRunner.query(`ALTER TABLE "Test_Options" ADD CONSTRAINT "FK_8a87c87410d9ef4f1c1948f0041" FOREIGN KEY ("question_id") REFERENCES "Test_Questions"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "App_User_Profiles" ADD CONSTRAINT "FK_9ed891feba1d9e0557c6c8672a9" FOREIGN KEY ("user_id") REFERENCES "App_Users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Tests" ADD CONSTRAINT "FK_c6aa9593c54cb6476c90254dbf6" FOREIGN KEY ("profile_id") REFERENCES "App_User_Profiles"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Test_Questions" ADD CONSTRAINT "FK_4f25b2e9b4e95d7b144038c7064" FOREIGN KEY ("test_id") REFERENCES "Tests"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Test_Results" ADD CONSTRAINT "FK_7c7ce13b45c411c30bf4dfac049" FOREIGN KEY ("attempt_id") REFERENCES "Test_Attempts"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Test_Results" ADD CONSTRAINT "FK_2f9f651b4fe27c51cb67f51f899" FOREIGN KEY ("question_id") REFERENCES "Test_Questions"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Test_Attempts" ADD CONSTRAINT "FK_1f45e771a78e8e360c34d02a334" FOREIGN KEY ("user_id") REFERENCES "App_Users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Test_Attempts" ADD CONSTRAINT "FK_da2edacb664d1c9165ab9ecab4e" FOREIGN KEY ("test_id") REFERENCES "Tests"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Log_Error" ADD CONSTRAINT "FK_f2cdda01c5851cfd0e4e6c59e64" FOREIGN KEY ("request_id") REFERENCES "Log_Request"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Log_Response" ADD CONSTRAINT "FK_555b924db8997f03ec49e416e4b" FOREIGN KEY ("request_id") REFERENCES "Log_Request"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Log_Request" ADD CONSTRAINT "FK_924b42905e2cd10ed5fa8200429" FOREIGN KEY ("user_id") REFERENCES "App_Users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Log_Request" ADD CONSTRAINT "FK_220f6ad9ab1e0e47f88b8d16f4b" FOREIGN KEY ("device_id") REFERENCES "Log_Device"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "App_Payment_Sessions" ADD CONSTRAINT "FK_bef4e7e8499e561639dd13e55f8" FOREIGN KEY ("payment_id") REFERENCES "App_Payments"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "App_Payments" ADD CONSTRAINT "FK_08d6052ea13763d91254f7e5528" FOREIGN KEY ("user_id") REFERENCES "App_Users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "App_Payments" ADD CONSTRAINT "FK_3cb58ed676f352851942d23ca19" FOREIGN KEY ("order_id") REFERENCES "App_Orders"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "App_Subscriptions" ADD CONSTRAINT "FK_2ddc95dad91a43ed491a933ca37" FOREIGN KEY ("user_id") REFERENCES "App_Users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "App_Subscriptions" ADD CONSTRAINT "FK_f6a5238b4fd16e1d6bf898b6a7e" FOREIGN KEY ("plan_id") REFERENCES "App_Plans"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "App_Subscriptions" ADD CONSTRAINT "FK_d86e000e8afdd37f11606af8575" FOREIGN KEY ("order_id") REFERENCES "App_Orders"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "App_Subscriptions" ADD CONSTRAINT "FK_3e3a004a337da6b08042b5e9fea" FOREIGN KEY ("payment_id") REFERENCES "App_Payments"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "App_Plans" ADD CONSTRAINT "FK_efb9f6680567e79829627588fa0" FOREIGN KEY ("node_id") REFERENCES "App_Nodes"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "App_Order_Amounts" ADD CONSTRAINT "FK_464ff7e099dfdf2712820b5a529" FOREIGN KEY ("order_id") REFERENCES "App_Orders"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "App_Orders" ADD CONSTRAINT "FK_ebfb0ad4a14142fa2d5fd896824" FOREIGN KEY ("user_id") REFERENCES "App_Users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "App_Orders" ADD CONSTRAINT "FK_5627a665b2dbd39f68666da05b8" FOREIGN KEY ("plan_id") REFERENCES "App_Plans"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Auth_Otps" ADD CONSTRAINT "FK_5c2c120d5a42a850ad5e123b5cf" FOREIGN KEY ("user_id") REFERENCES "App_Users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Auth_Provider" ADD CONSTRAINT "FK_75cc0f95a7e59c08a6ec579f23d" FOREIGN KEY ("user_id") REFERENCES "App_Users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Auth_Sessions" ADD CONSTRAINT "FK_24ac36e83804ccbeb26ace1cec5" FOREIGN KEY ("user_id") REFERENCES "App_Users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Auth_Tokens" ADD CONSTRAINT "FK_bae56796632f106013f291ff87d" FOREIGN KEY ("user_id") REFERENCES "App_Users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Acd_Comparison_Items" ADD CONSTRAINT "FK_e63595f428f303f5a78d5f7e875" FOREIGN KEY ("comparison_id") REFERENCES "Acd_Comparisons"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Acd_Content_Comparisons" ADD CONSTRAINT "FK_ab748a39ca52b1bbebb15a6cda0" FOREIGN KEY ("content_id") REFERENCES "Acd_Content"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Acd_Content_Comparisons" ADD CONSTRAINT "FK_fa6954e3e11fd5a22472d511958" FOREIGN KEY ("comparison_id") REFERENCES "Acd_Comparisons"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Acd_Content_Diagrams" ADD CONSTRAINT "FK_dbc665ea303c0643c7ccf5d3dd8" FOREIGN KEY ("content_id") REFERENCES "Acd_Content"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Acd_Content_Diagrams" ADD CONSTRAINT "FK_f3dccdd9523f9f7b0589f2dccaa" FOREIGN KEY ("diagram_id") REFERENCES "Acd_Diagrams"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Acd_Content" ADD CONSTRAINT "FK_e4ddc086a58479dcdd36e6099bd" FOREIGN KEY ("topic_id") REFERENCES "Acd_Syllabus"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Acd_Syllabus" ADD CONSTRAINT "FK_c0f37b5aadc0bedbde1863c7dba" FOREIGN KEY ("parent_id") REFERENCES "Acd_Syllabus"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "Acd_Syllabus" DROP CONSTRAINT "FK_c0f37b5aadc0bedbde1863c7dba"`);
        await queryRunner.query(`ALTER TABLE "Acd_Content" DROP CONSTRAINT "FK_e4ddc086a58479dcdd36e6099bd"`);
        await queryRunner.query(`ALTER TABLE "Acd_Content_Diagrams" DROP CONSTRAINT "FK_f3dccdd9523f9f7b0589f2dccaa"`);
        await queryRunner.query(`ALTER TABLE "Acd_Content_Diagrams" DROP CONSTRAINT "FK_dbc665ea303c0643c7ccf5d3dd8"`);
        await queryRunner.query(`ALTER TABLE "Acd_Content_Comparisons" DROP CONSTRAINT "FK_fa6954e3e11fd5a22472d511958"`);
        await queryRunner.query(`ALTER TABLE "Acd_Content_Comparisons" DROP CONSTRAINT "FK_ab748a39ca52b1bbebb15a6cda0"`);
        await queryRunner.query(`ALTER TABLE "Acd_Comparison_Items" DROP CONSTRAINT "FK_e63595f428f303f5a78d5f7e875"`);
        await queryRunner.query(`ALTER TABLE "Auth_Tokens" DROP CONSTRAINT "FK_bae56796632f106013f291ff87d"`);
        await queryRunner.query(`ALTER TABLE "Auth_Sessions" DROP CONSTRAINT "FK_24ac36e83804ccbeb26ace1cec5"`);
        await queryRunner.query(`ALTER TABLE "Auth_Provider" DROP CONSTRAINT "FK_75cc0f95a7e59c08a6ec579f23d"`);
        await queryRunner.query(`ALTER TABLE "Auth_Otps" DROP CONSTRAINT "FK_5c2c120d5a42a850ad5e123b5cf"`);
        await queryRunner.query(`ALTER TABLE "App_Orders" DROP CONSTRAINT "FK_5627a665b2dbd39f68666da05b8"`);
        await queryRunner.query(`ALTER TABLE "App_Orders" DROP CONSTRAINT "FK_ebfb0ad4a14142fa2d5fd896824"`);
        await queryRunner.query(`ALTER TABLE "App_Order_Amounts" DROP CONSTRAINT "FK_464ff7e099dfdf2712820b5a529"`);
        await queryRunner.query(`ALTER TABLE "App_Plans" DROP CONSTRAINT "FK_efb9f6680567e79829627588fa0"`);
        await queryRunner.query(`ALTER TABLE "App_Subscriptions" DROP CONSTRAINT "FK_3e3a004a337da6b08042b5e9fea"`);
        await queryRunner.query(`ALTER TABLE "App_Subscriptions" DROP CONSTRAINT "FK_d86e000e8afdd37f11606af8575"`);
        await queryRunner.query(`ALTER TABLE "App_Subscriptions" DROP CONSTRAINT "FK_f6a5238b4fd16e1d6bf898b6a7e"`);
        await queryRunner.query(`ALTER TABLE "App_Subscriptions" DROP CONSTRAINT "FK_2ddc95dad91a43ed491a933ca37"`);
        await queryRunner.query(`ALTER TABLE "App_Payments" DROP CONSTRAINT "FK_3cb58ed676f352851942d23ca19"`);
        await queryRunner.query(`ALTER TABLE "App_Payments" DROP CONSTRAINT "FK_08d6052ea13763d91254f7e5528"`);
        await queryRunner.query(`ALTER TABLE "App_Payment_Sessions" DROP CONSTRAINT "FK_bef4e7e8499e561639dd13e55f8"`);
        await queryRunner.query(`ALTER TABLE "Log_Request" DROP CONSTRAINT "FK_220f6ad9ab1e0e47f88b8d16f4b"`);
        await queryRunner.query(`ALTER TABLE "Log_Request" DROP CONSTRAINT "FK_924b42905e2cd10ed5fa8200429"`);
        await queryRunner.query(`ALTER TABLE "Log_Response" DROP CONSTRAINT "FK_555b924db8997f03ec49e416e4b"`);
        await queryRunner.query(`ALTER TABLE "Log_Error" DROP CONSTRAINT "FK_f2cdda01c5851cfd0e4e6c59e64"`);
        await queryRunner.query(`ALTER TABLE "Test_Attempts" DROP CONSTRAINT "FK_da2edacb664d1c9165ab9ecab4e"`);
        await queryRunner.query(`ALTER TABLE "Test_Attempts" DROP CONSTRAINT "FK_1f45e771a78e8e360c34d02a334"`);
        await queryRunner.query(`ALTER TABLE "Test_Results" DROP CONSTRAINT "FK_2f9f651b4fe27c51cb67f51f899"`);
        await queryRunner.query(`ALTER TABLE "Test_Results" DROP CONSTRAINT "FK_7c7ce13b45c411c30bf4dfac049"`);
        await queryRunner.query(`ALTER TABLE "Test_Questions" DROP CONSTRAINT "FK_4f25b2e9b4e95d7b144038c7064"`);
        await queryRunner.query(`ALTER TABLE "Tests" DROP CONSTRAINT "FK_c6aa9593c54cb6476c90254dbf6"`);
        await queryRunner.query(`ALTER TABLE "App_User_Profiles" DROP CONSTRAINT "FK_9ed891feba1d9e0557c6c8672a9"`);
        await queryRunner.query(`ALTER TABLE "Test_Options" DROP CONSTRAINT "FK_8a87c87410d9ef4f1c1948f0041"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0224d21448d8783d139eac78d0"`);
        await queryRunner.query(`DROP TABLE "Acd_Syllabus"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_560dc931b4dc9612e76f82d895"`);
        await queryRunner.query(`DROP TABLE "Acd_Content"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4d8eee0c7b3c262871bfa18fae"`);
        await queryRunner.query(`DROP TABLE "Acd_Content_Diagrams"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0afdeeb26439230aaad1781b84"`);
        await queryRunner.query(`DROP TABLE "Acd_Diagrams"`);
        await queryRunner.query(`DROP TYPE "public"."Acd_Diagrams_media_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_afd2e3a74c2a30644f01bdd567"`);
        await queryRunner.query(`DROP TABLE "Acd_Content_Comparisons"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b9186fb1076d51cd39cb15fffd"`);
        await queryRunner.query(`DROP TABLE "Acd_Comparisons"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5a5d0b1f14fb947aa113e2bd9d"`);
        await queryRunner.query(`DROP TABLE "Acd_Comparison_Items"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c3fae2f7847b5213ffbe1cb420"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6f469e31117c95894c704439e4"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_fb1541780676fa4a65deb2be35"`);
        await queryRunner.query(`DROP TABLE "Meta_Geo_Continents"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e0730a0f54072c62ee1db7289e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_878a859c3a839a147600c5b6d8"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_dcc675fb08047c471b4586f04d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3b1e427ac63835522ff5c43de3"`);
        await queryRunner.query(`DROP TABLE "Meta_Geo_Countries"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6fed9764eca9a263e61e64f108"`);
        await queryRunner.query(`DROP TABLE "Meta_Geo_Deserts"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_45e21d6a72e63d8e0f249bbf39"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_603679fe3b2fe61026e40ff683"`);
        await queryRunner.query(`DROP TABLE "Meta_Geo_Rivers"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b075f4336109e9bab5818631ba"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c5353e390a3d545087d02c929b"`);
        await queryRunner.query(`DROP TABLE "Meta_Geo_Water_Bodies"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_752fbf19f9ef9241b729d51865"`);
        await queryRunner.query(`DROP TABLE "Meta_Global_Orgs"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3dafe8e504d69068a2e4028a57"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2498407c7c048a8143d41bc52f"`);
        await queryRunner.query(`DROP TABLE "App_Clients"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ea7d09e61982b98a9920bdbc5e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_df1ac31e41efe8e985fdae0dbb"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d31d7ce68d9bf75a11d957f81a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1dd1db41c4a33bc92121e05fb7"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_156a9fed402cb96e877f4ca8e9"`);
        await queryRunner.query(`DROP TABLE "App_Users"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_80f1763d5cfafc4a5193d89b1e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_27d3dfde29b373d2969098de75"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_73f288724f093c6cbe774fe5e9"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ad32f77582c45444d25ecaa683"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_35d298e0b7d4f5204017045752"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ea60f81fb3a3df93407a9dbe99"`);
        await queryRunner.query(`DROP TABLE "Auth_Tokens"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ed2a5de64bf5f1719e13506b8e"`);
        await queryRunner.query(`DROP TABLE "Auth_Sessions"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_cefcb8861290ef1baaf964c409"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_feab35e90893152d0f6b3f0fbc"`);
        await queryRunner.query(`DROP TABLE "Auth_Provider"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_149d33f5b681601f1226a9cc29"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ff6502b8ebdc94a9a7a73e197b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_418897925b209bfd2b5807b29f"`);
        await queryRunner.query(`DROP TABLE "Auth_Otps"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0cea8e3843fe84e3ca2d387dc0"`);
        await queryRunner.query(`DROP TABLE "App_Orders"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3656c9c243379c7573c4000404"`);
        await queryRunner.query(`DROP TABLE "App_Order_Amounts"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4c065ef3cc4a44f4327f3d043f"`);
        await queryRunner.query(`DROP TABLE "App_Plans"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a996499aa7897bb9715b7022f4"`);
        await queryRunner.query(`DROP TABLE "App_Nodes"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0d77c4c930691c477603bb006e"`);
        await queryRunner.query(`DROP TABLE "App_Subscriptions"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_17af54eb164f22204f7b6446a3"`);
        await queryRunner.query(`DROP TABLE "App_Payments"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f4a1fe1deebded3e06e3849c7d"`);
        await queryRunner.query(`DROP TABLE "App_Payment_Sessions"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f5aff5920114252b7d12c0549e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_220f6ad9ab1e0e47f88b8d16f4"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_924b42905e2cd10ed5fa820042"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c3808f42fcaf7082d2ea37fda9"`);
        await queryRunner.query(`DROP TABLE "Log_Request"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ccc883b42da57062abb6520f5b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_555b924db8997f03ec49e416e4"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b237ff6093ab521eaf9ad50dac"`);
        await queryRunner.query(`DROP TABLE "Log_Response"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6278117936c7c8d2ed850a5394"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_17f330d29e4f9285a797f0fce8"`);
        await queryRunner.query(`DROP TABLE "Log_Error"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f4ba3cd398bf8188701139816a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f270a3832892a35339040fef36"`);
        await queryRunner.query(`DROP TABLE "Log_Device"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_da2edacb664d1c9165ab9ecab4"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1f45e771a78e8e360c34d02a33"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_66f0b945db916893c35c8002a8"`);
        await queryRunner.query(`DROP TABLE "Test_Attempts"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_985af56efa4dc0a270541c789c"`);
        await queryRunner.query(`DROP TABLE "Test_Results"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a61ea4effa78ec28c32898ecf8"`);
        await queryRunner.query(`DROP TABLE "Test_Questions"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_64534a51882e89c399fb7f17a9"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9bb6c33098886ef04153a3f615"`);
        await queryRunner.query(`DROP TABLE "Tests"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_946e625be5e5b268ad2675ec09"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2b52ef874ff0a6b8698a409035"`);
        await queryRunner.query(`DROP TABLE "App_User_Profiles"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b3463f4f4fc498924213c0fc1d"`);
        await queryRunner.query(`DROP TABLE "Test_Options"`);
    }

}
