services:
  api:
    build:
      context: .
      # Allows passing version at build time if needed
      args:
        - VERSION=${APP_VERSION:-latest}
    # Uses a variable for the image tag
    image: ${DOCKER_REGISTRY:-local}/saadana-api:${APP_VERSION:-latest}
    container_name: saadana-api
    # user: "1000:1000"
    restart: always
    env_file: .env
    volumes:
      # Left side: Host Path | Right side: Container Path
      - ../saadana-logs/api-logs:/app/logs
      - ../saadana-data/meta:/app/meta
      - ../saadana-data/seed:/app/seed
    labels:
      - "traefik.enable=true"
      # Dynamic Host: api.localhost for dev, api.yourdomain.com for prod
      - "traefik.http.routers.saadana-api.rule=Host(`${API_HOST}`)"
      - "traefik.http.routers.saadana-api.entrypoints=web"
      - "traefik.http.services.saadana-api.loadbalancer.server.port=3000"
    networks:
      - saadana-network

networks:
  saadana-network:
    external: true